### ISSUE TITLE
gitee 和 github 账号无法登陆

### ISSUE THREAD

**Issue by 2622019635** [hbrwang/Lavcode#5]
使用 gitee 或者 github 账号登录的时候，一直处于登录界面，无法进入。
浏览器使用的是 opera，系统是 windows11，gitee 和 github 也进行了第三方授权

**Comment by hal-wang** [comment]
> 使用 gitee 或者 github 账号登录的时候，一直处于登录界面，无法进入。 浏览器使用的是 opera，系统是 windows11，gitee 和 github 也进行了第三方授权

经过测试 opera 也是可以正常登录的，相关版本：

- Lavcode版本：1.0.1 Beta 和 1.0.0 Beta
- Opera版本：82.0.4227.43
- 系统版本：win10 21H1 和 win11 21H2

---

授权后，浏览器弹出的对话框，你是否已点击“打开Lavcode”按钮呢？

![image](https://user-images.githubusercontent.com/39717597/147895774-6922e739-99f1-496d-a8b2-ffcede0bf5c7.png)

**Comment by 2622019635** [comment]
点击了，已经对软件进行授权后尝试登录，但是无法进入软件，只有在选择本地存储时才能成功进入软件
![示范](https://user-images.githubusercontent.com/61149488/148140012-787b533a-b0b0-452f-8864-896e994813be.gif)

**Comment by 2622019635** [comment]
Lavcode版本：1.0.1 Beta
来源：微软应用商店

**Comment by hal-wang** [comment]
抱歉，我暂时没能复现这个问题。你可以尝试备份后重置应用，看下能不能解决

**Comment by hal-wang** [comment]
有可能是因为网络连接失败，但没有提示出来，在1.0.2版本中加了错误提示，现在1.0.2版本已提交待审核。

另外请确认没有使用代理软件，代理软件会让商店应用无法访问网络

**Comment by 2622019635** [comment]
现在确实是显示网络连接失败，并且在打开代理和关闭代理的情况下都有尝试过，不清楚是什么问题

**Comment by hal-wang** [comment]
由于如果没有更多人出现这个问题，我现在关闭此 Issue ，如果仍有此问题我会再打开
